name: Deploy Release Notes

on:
  push:
    branches:
      - gh-page # Chạy mỗi khi bạn push code mới lên nhánh main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies & Build
        run: |
          cd my-release-notes
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: my-release-notes/build # Thư mục sau khi build thành HTML
          branch: gh-pages # Đẩy lên nhánh này để hiển thị ra ngoài internet
